/**
 * The GRC lab generator engine.
 *
 * Dynamically generates structured GRC lab exercises based on the current
 * environment state (findings and risk register). When a local Ollama model
 * is available, the lab is generated by the model and grounded with knowledge
 * base articles. When Ollama is not running, a deterministic, template-based
 * lab is produced from the request so the learner always has a usable
 * exercise.
 *
 * The engine mirrors the GRC Senior Expert tutor (`@/vm/grcExpert`): it
 * retrieves from the knowledge base first, grounds the model prompt with the
 * learner's actual findings and risk register, and falls back to an offline
 * template when the local model is unavailable.
 */

import { ollamaAvailable, OLLAMA_GENERATE_URL, OLLAMA_MODEL } from '@/config/ollama';
import { searchArticles, type Article } from '@/config/knowledgeBase';

/* ------------------------------------------------------------------ *
 * Types
 * ------------------------------------------------------------------ */

export type LabCategory =
  | 'audit'
  | 'risk'
  | 'remediation'
  | 'policy'
  | 'executive'
  | 'compliance'
  | 'incident';

export type LabDifficulty = 'Beginner' | 'Intermediate' | 'Advanced';

export interface GeneratedLab {
  title: string;
  category: LabCategory;
  difficulty: LabDifficulty;
  objective: string;
  steps: string[];
  deliverables: string[];
  verificationCriteria: string[];
  estimatedTime: string;
  source: 'ollama' | 'offline';
}

export interface LabGenerationRequest {
  category: LabCategory;
  difficulty: LabDifficulty;
  findings: { id: string; title: string; severity: string; status: string }[];
  risks: { id: string; finding: string; inherentRisk: number }[];
}

/* ------------------------------------------------------------------ *
 * Category / difficulty metadata
 * ------------------------------------------------------------------ */

export const LAB_CATEGORIES: {
  id: LabCategory;
  label: string;
  description: string;
}[] = [
  {
    id: 'audit',
    label: 'Audit & Discovery',
    description:
      'Discover, document, and map findings to compliance frameworks using the Audit Console and Terminal.',
  },
  {
    id: 'risk',
    label: 'Risk Assessment',
    description:
      'Score findings on the risk matrix and add entries to the Risk Register.',
  },
  {
    id: 'remediation',
    label: 'Remediation',
    description:
      'Fix findings in the Remediation Console, verify the fix, and re-audit the control.',
  },
  {
    id: 'policy',
    label: 'Policy Writing',
    description:
      'Draft, review, and enforce a security policy addressing a finding using the Policy Console.',
  },
  {
    id: 'executive',
    label: 'Executive Briefing',
    description:
      'Brief executives on a finding using financial framing and budget defense in the GRC Expert.',
  },
  {
    id: 'compliance',
    label: 'Compliance Mapping',
    description:
      'Map a finding to a specific framework with control citation and gap analysis.',
  },
  {
    id: 'incident',
    label: 'Incident Response',
    description:
      'Respond to a finding as a security incident: detect, contain, eradicate, and report.',
  },
];

export const LAB_DIFFICULTIES: LabDifficulty[] = [
  'Beginner',
  'Intermediate',
  'Advanced',
];

/** Re-export the Ollama liveness check under the generator's own name. */
export function labAvailable(): Promise<boolean> {
  return ollamaAvailable();
}

/* ------------------------------------------------------------------ *
 * Offline template labs
 * ------------------------------------------------------------------ */

/** Human-readable label for each category, for inline use in templates. */
const CATEGORY_LABEL: Record<LabCategory, string> = {
  audit: 'Audit & Discovery',
  risk: 'Risk Assessment',
  remediation: 'Remediation',
  policy: 'Policy Writing',
  executive: 'Executive Briefing',
  compliance: 'Compliance Mapping',
  incident: 'Incident Response',
};

/**
 * Pick a representative finding to anchor the lab on.
 *
 * Prefers the highest-severity open finding; falls back to the first finding
 * or a generic placeholder when the environment has no findings yet.
 */
function anchorFinding(
  req: LabGenerationRequest,
): { id: string; title: string; severity: string; status: string } {
  const severityRank: Record<string, number> = {
    Critical: 4,
    High: 3,
    Medium: 2,
    Low: 1,
  };
  const open = req.findings.filter((f) => f.status !== 'Remediated');
  const pool = open.length > 0 ? open : req.findings;
  if (pool.length === 0) {
    return {
      id: 'GENERIC-001',
      title: 'a generic compliance gap',
      severity: 'Medium',
      status: 'Open',
    };
  }
  let best = pool[0];
  if (!best) return { id: 'GENERIC-001', title: 'a generic compliance gap', severity: 'Medium', status: 'Open' };
  for (const f of pool) {
    const cur = severityRank[best.severity] ?? 0;
    const cand = severityRank[f.severity] ?? 0;
    if (cand > cur) best = f;
  }
  return best;
}

/** Format the findings list for embedding in lab steps. */
function findingsList(req: LabGenerationRequest): string {
  if (req.findings.length === 0) return 'No findings recorded yet.';
  return req.findings
    .map((f) => `- ${f.id} [${f.severity}/${f.status}] ${f.title}`)
    .join('\n');
}

/** Format the risk register for embedding in lab steps. */
function risksList(req: LabGenerationRequest): string {
  if (req.risks.length === 0) return 'No risks recorded yet.';
  return req.risks
    .map((r) => `- ${r.id} (inherent risk ${r.inherentRisk}) ${r.finding}`)
    .join('\n');
}

/** Estimated time for a given difficulty. */
function timeFor(difficulty: LabDifficulty): string {
  switch (difficulty) {
    case 'Beginner':
      return '20-30 minutes';
    case 'Intermediate':
      return '30-45 minutes';
    case 'Advanced':
      return '45-60 minutes';
  }
}

/**
 * Produce a deterministic, template-based lab without Ollama.
 *
 * Each category has its own template that references the actual findings and
 * risk register from the request, names the real app tools (Audit Console,
 * Risk Register, Remediation Console, Terminal, GRC Expert), and produces
 * concrete steps, deliverables, and verification criteria.
 */
export function offlineLab(req: LabGenerationRequest): GeneratedLab {
  const anchor = anchorFinding(req);
  const findings = findingsList(req);
  const risks = risksList(req);
  const time = timeFor(req.difficulty);

  switch (req.category) {
    case 'audit':
      return {
        title: `Audit the ${anchor.title} — discover, document, and map to frameworks`,
        category: 'audit',
        difficulty: req.difficulty,
        objective: `Discover and document the "${anchor.title}" finding (${anchor.id}), capture audit evidence, and map it to the relevant compliance frameworks (PCI-DSS, HIPAA, GDPR, ISO 27001, NIST CSF, CIS, SOC 2).`,
        steps: [
          `Open the Audit Console and review the current findings list. Confirm ${anchor.id} [${anchor.severity}/${anchor.status}] "${anchor.title}" is present.`,
          `Open the Terminal and run the discovery cmdlet that surfaces the evidence for ${anchor.id} (e.g. share ACL listing, local group membership, or a file-content scan). Capture the raw output.`,
          `Document the finding in the Audit Console: record the asset, the control that is violated, the evidence captured, and the severity justification.`,
          `Map ${anchor.id} to each applicable framework. For each, cite the specific control or requirement number (e.g. PCI-DSS 3.4, ISO 27001 A.9.4.2, NIST CSF PR.AC-4).`,
          `Cross-reference the finding against the current risk register entries:\n${risks}`,
          `Use the GRC Expert (walkthrough mode) to confirm your control citations are correct for "${anchor.title}".`,
          `Compile the full audit evidence package: raw output, finding record, and framework mapping for ${anchor.id}.`,
        ],
        deliverables: [
          `Audit evidence file for ${anchor.id} containing the raw discovery output.`,
          `A completed finding record in the Audit Console for "${anchor.title}" with severity and status.`,
          `A framework mapping table citing at least three controls across PCI-DSS, ISO 27001, and NIST CSF.`,
          `A short note from the GRC Expert confirming the control citations.`,
        ],
        verificationCriteria: [
          `${anchor.id} appears in the Audit Console with a documented evidence path.`,
          `At least three framework control citations are recorded for "${anchor.title}".`,
          `The raw discovery output is attached as evidence and reproducible from the Terminal.`,
          `The finding severity matches the evidence (no Critical downgraded to Low without justification).`,
        ],
        estimatedTime: time,
        source: 'offline',
      };

    case 'risk':
      return {
        title: `Risk assess the ${anchor.title} — score, matrix, and register entry`,
        category: 'risk',
        difficulty: req.difficulty,
        objective: `Perform a risk assessment for "${anchor.title}" (${anchor.id}): determine likelihood and impact, plot it on the risk matrix, and add a complete entry to the Risk Register.`,
        steps: [
          `Open the Audit Console and review the evidence for ${anchor.id} [${anchor.severity}/${anchor.status}] "${anchor.title}".`,
          `Determine the likelihood of exploitation given the current control state. Use the Terminal to confirm any exposed surfaces (open shares, weak passwords, group sprawl).`,
          `Determine the business impact should the finding be exploited. Consider data sensitivity (PAN, ePHI, SSN) and regulatory exposure.`,
          `Plot the likelihood x impact on the risk matrix to derive the inherent risk score for ${anchor.id}.`,
          `Open the Risk Register and add a new entry for "${anchor.title}": finding id, description, inherent risk score, and the justification.`,
          `Review the current register and confirm the new entry is consistent with existing risks:\n${risks}`,
          `Use the GRC Expert (explain mode) to validate your inherent risk score against the knowledge base.`,
        ],
        deliverables: [
          `A completed Risk Register entry for ${anchor.id} with inherent risk score and justification.`,
          `A marked-up risk matrix showing where "${anchor.title}" lands.`,
          `A likelihood and impact rationale citing the evidence from the Terminal and Audit Console.`,
          `An updated risk register export showing the new entry alongside existing risks.`,
        ],
        verificationCriteria: [
          `The Risk Register contains a new entry for ${anchor.id} with a numeric inherent risk score.`,
          `The inherent risk score is consistent with the ${anchor.severity} severity of the finding.`,
          `The likelihood and impact rationale references concrete evidence (share ACLs, group membership, data type).`,
          `The GRC Expert did not flag the score as inconsistent with the knowledge base.`,
        ],
        estimatedTime: time,
        source: 'offline',
      };

    case 'remediation':
      return {
        title: `Remediate the ${anchor.title} — fix, verify, and re-audit`,
        category: 'remediation',
        difficulty: req.difficulty,
        objective: `Remediate "${anchor.title}" (${anchor.id}) in the Remediation Console, verify the fix in the Terminal, and re-audit the control to confirm the finding is closed.`,
        steps: [
          `Open the Remediation Console and select ${anchor.id} [${anchor.severity}/${anchor.status}] "${anchor.title}".`,
          `Identify the remediation action: restrict the ACL, remove the account, encrypt the data, or update the policy as appropriate for "${anchor.title}".`,
          `Execute the remediation in the Terminal (e.g. net share, icacls, net localgroup, Set-LocalUser) and capture the before and after output.`,
          `Mark the remediation complete in the Remediation Console and attach the before/after evidence to ${anchor.id}.`,
          `Re-run the discovery cmdlet from the Audit Console to verify the control now passes for "${anchor.title}".`,
          `Update the Risk Register entry for ${anchor.id} to reflect the reduced residual risk.`,
          `Use the GRC Expert (walkthrough mode) to confirm the remediation fully closes the control gap.`,
        ],
        deliverables: [
          `Before and after Terminal output showing the remediation of ${anchor.id}.`,
          `A Remediation Console record for "${anchor.title}" marked complete with evidence attached.`,
          `A re-audit result from the Audit Console confirming the control passes.`,
          `An updated Risk Register entry showing reduced residual risk for ${anchor.id}.`,
        ],
        verificationCriteria: [
          `The Terminal before/after output demonstrates the control change for "${anchor.title}".`,
          `${anchor.id} is marked Remediated in the Audit Console.`,
          `The re-audit discovery cmdlet no longer flags "${anchor.title}".`,
          `The Risk Register residual risk for ${anchor.id} is lower than the inherent risk.`,
        ],
        estimatedTime: time,
        source: 'offline',
      };

    case 'policy':
      return {
        title: `Write a policy for ${anchor.title} — draft, review, and enforce`,
        category: 'policy',
        difficulty: req.difficulty,
        objective: `Draft a security policy that addresses "${anchor.title}" (${anchor.id}), review it against the relevant framework, and define the enforcement mechanism.`,
        steps: [
          `Open the Audit Console and review the evidence for ${anchor.id} to understand the control gap "${anchor.title}" represents.`,
          `Identify the policy domain (access control, data protection, password, incident response) that "${anchor.title}" falls under.`,
          `Draft the policy in the Policy Console: scope, roles, requirements, exceptions, and review cycle.`,
          `Map each policy requirement to a specific framework control (e.g. ISO 27001 A.9, NIST CSF PR.AC, PCI-DSS) and cite it inline.`,
          `Define the enforcement mechanism: technical control (ACL, GPO), monitoring (audit log), and the owner accountable for each requirement.`,
          `Review the draft against the current findings to ensure it would have prevented ${anchor.id}:\n${findings}`,
          `Use the GRC Expert (explain mode) to validate the policy against the knowledge base.`,
        ],
        deliverables: [
          `A drafted policy document in the Policy Console addressing "${anchor.title}".`,
          `A control mapping table linking each policy requirement to a framework control.`,
          `An enforcement plan naming the technical control, monitoring, and accountable owner.`,
          `A review note confirming the policy would have prevented ${anchor.id}.`,
        ],
        verificationCriteria: [
          `The policy document has scope, roles, requirements, exceptions, and a review cycle.`,
          `Each requirement is mapped to at least one framework control citation.`,
          `The enforcement plan names a concrete technical control and an accountable owner.`,
          `The GRC Expert confirms the policy is consistent with the knowledge base.`,
        ],
        estimatedTime: time,
        source: 'offline',
      };

    case 'executive':
      return {
        title: `Brief executives on ${anchor.title} — financial framing and budget defense`,
        category: 'executive',
        difficulty: req.difficulty,
        objective: `Prepare and deliver an executive briefing on "${anchor.title}" (${anchor.id}) framed in financial risk terms, and defend the remediation budget against a skeptical CFO.`,
        steps: [
          `Open the Audit Console and review ${anchor.id} [${anchor.severity}/${anchor.status}] "${anchor.title}" and its business impact.`,
          `Translate the technical finding into financial terms: potential fine (e.g. GDPR 4% of turnover), breach cost, and remediation cost.`,
          `Open the Risk Register and cite the inherent risk score for ${anchor.id} as the quantitative basis:\n${risks}`,
          `Draft the one-page executive briefing: the risk, the financial exposure, the recommended action, and the cost.`,
          `Use the GRC Expert to role-play a skeptical CFO challenging the budget. Defend the spend using risk-reduction metrics.`,
          `Revise the briefing based on the CFO challenge: tighten the financial framing and add a cost-of-inaction comparison.`,
          `Finalize the briefing and attach the supporting risk register and audit evidence.`,
        ],
        deliverables: [
          `A one-page executive briefing on "${anchor.title}" in financial terms.`,
          `A financial exposure estimate citing the applicable fine structure (GDPR, HIPAA, PCI-DSS).`,
          `A record of the CFO challenge and the defense responses from the GRC Expert session.`,
          `A revised briefing incorporating the budget defense.`,
        ],
        verificationCriteria: [
          `The briefing states the risk, financial exposure, recommended action, and cost on a single page.`,
          `The financial exposure cites a specific fine structure or breach cost figure.`,
          `The budget defense survives a GRC Expert CFO challenge with concrete risk-reduction metrics.`,
          `The briefing references the inherent risk score from the Risk Register for ${anchor.id}.`,
        ],
        estimatedTime: time,
        source: 'offline',
      };

    case 'compliance':
      return {
        title: `Map ${anchor.title} to framework — control citation and gap analysis`,
        category: 'compliance',
        difficulty: req.difficulty,
        objective: `Perform a detailed compliance mapping and gap analysis for "${anchor.title}" (${anchor.id}) against a chosen framework, citing the specific controls and documenting the gap.`,
        steps: [
          `Select the target framework for the mapping (PCI-DSS, HIPAA, GDPR, ISO 27001, NIST CSF, CIS, or SOC 2) based on the data type in "${anchor.title}".`,
          `Open the Audit Console and review the evidence for ${anchor.id} to understand the exact control failure.`,
          `Identify the specific control or requirement in the framework that "${anchor.title}" violates (e.g. PCI-DSS 3.4, ISO 27001 A.9.4.2).`,
          `Document the gap: the required control state versus the current state evidenced for ${anchor.id}.`,
          `Cross-check the mapping against the knowledge base using the GRC Expert (explain mode).`,
          `Produce a gap analysis table: control citation, current state, required state, gap severity, and remediation owner.`,
          `Review the current findings to confirm no related controls are missed:\n${findings}`,
        ],
        deliverables: [
          `A gap analysis table for "${anchor.title}" with control citations and current/required states.`,
          `The specific framework control number(s) violated by ${anchor.id}.`,
          `A gap severity rating and a named remediation owner for each gap.`,
          `A GRC Expert note confirming the control citations are accurate.`,
        ],
        verificationCriteria: [
          `The gap analysis cites at least one specific control number from the chosen framework.`,
          `The current state is backed by evidence from the Audit Console for ${anchor.id}.`,
          `Each gap has a severity rating and a remediation owner.`,
          `The GRC Expert did not contradict the control citations.`,
        ],
        estimatedTime: time,
        source: 'offline',
      };

    case 'incident':
      return {
        title: `Respond to a ${anchor.title} incident — detect, contain, and report`,
        category: 'incident',
        difficulty: req.difficulty,
        objective: `Treat "${anchor.title}" (${anchor.id}) as a live security incident and walk through detection, containment, eradication, recovery, and reporting.`,
        steps: [
          `Open the Audit Console and treat ${anchor.id} [${anchor.severity}/${anchor.status}] "${anchor.title}" as a detected incident.`,
          `Detect: confirm the indicator of compromise using the Terminal (e.g. open share, exposed data, rogue account).`,
          `Contain: take immediate action to stop the exposure — restrict the ACL, disable the account, or isolate the asset — and capture the action in the Terminal.`,
          `Eradicate: remove the root cause (delete the cleartext file, remove the rogue account, rotate the weak password) for "${anchor.title}".`,
          `Recover: restore the asset to a known-good state and verify normal operation with a follow-up discovery scan.`,
          `Report: document the incident timeline, actions taken, and regulatory notification obligations (e.g. HIPAA 60-day, GDPR 72-hour) in the incident record.`,
          `Use the GRC Expert (walkthrough mode) to confirm the response covers detection, containment, eradication, recovery, and reporting.`,
        ],
        deliverables: [
          `An incident timeline documenting detection through recovery for ${anchor.id}.`,
          `Terminal output showing the containment and eradication actions for "${anchor.title}".`,
          `A recovery verification showing the asset is back to a known-good state.`,
          `An incident report with the regulatory notification obligation and deadline identified.`,
        ],
        verificationCriteria: [
          `The incident timeline covers detect, contain, eradicate, recover, and report phases.`,
          `Containment actions are evidenced by Terminal output.`,
          `The recovery scan confirms "${anchor.title}" is no longer exploitable.`,
          `The report identifies the correct regulatory notification deadline for the data type.`,
        ],
        estimatedTime: time,
        source: 'offline',
      };
  }
}

/* ------------------------------------------------------------------ *
 * Prompt construction
 * ------------------------------------------------------------------ */

/** The system instruction for the lab generator model. */
const SYSTEM_PROMPT =
  'You are a GRC lab generator. Generate a structured lab exercise as plain text with sections: TITLE, OBJECTIVE, STEPS (numbered), DELIVERABLES, VERIFICATION, TIME. No markdown.';

/** A short instruction per category to steer the model. */
const CATEGORY_INSTRUCTION: Record<LabCategory, string> = {
  audit:
    'The lab is an audit/discovery exercise: the learner discovers a finding, documents evidence, and maps it to frameworks.',
  risk:
    'The lab is a risk assessment exercise: the learner scores the finding on a risk matrix and adds a Risk Register entry.',
  remediation:
    'The lab is a remediation exercise: the learner fixes the finding, verifies the fix, and re-audits the control.',
  policy:
    'The lab is a policy-writing exercise: the learner drafts a policy addressing the finding and maps requirements to controls.',
  executive:
    'The lab is an executive-briefing exercise: the learner frames the finding in financial terms and defends the budget.',
  compliance:
    'The lab is a compliance-mapping exercise: the learner maps the finding to a specific framework with control citations and gap analysis.',
  incident:
    'The lab is an incident-response exercise: the learner detects, contains, eradicates, recovers, and reports the finding as an incident.',
};

/** Format the request's findings and risks for the prompt. */
function formatRequest(req: LabGenerationRequest): string {
  const findings = req.findings.length
    ? req.findings
        .map((f) => `- ${f.id} [${f.severity}/${f.status}] ${f.title}`)
        .join('\n')
    : '- (no findings recorded)';
  const risks = req.risks.length
    ? req.risks
        .map((r) => `- ${r.id} (inherent risk ${r.inherentRisk}) ${r.finding}`)
        .join('\n')
    : '- (no risks recorded)';
  return `Current findings:\n${findings}\n\nCurrent risk register:\n${risks}`;
}

/** Format retrieved knowledge base articles as grounding material. */
function formatCitations(articles: Article[]): string {
  if (articles.length === 0) return 'No directly matching reference material was found.';
  return articles
    .map(
      (a, i) =>
        `Reference ${i + 1} [${a.id}] ${a.title} (topic: ${a.topic})\n${a.body}`,
    )
    .join('\n\n');
}

/** Build the full prompt sent to Ollama. */
function buildPrompt(
  req: LabGenerationRequest,
  citations: Article[],
): string {
  return [
    SYSTEM_PROMPT,
    CATEGORY_INSTRUCTION[req.category],
    `Category: ${CATEGORY_LABEL[req.category]}`,
    `Difficulty: ${req.difficulty}`,
    '',
    formatRequest(req),
    '',
    'Reference material:',
    formatCitations(citations),
    '',
    'Generate the lab now, using this exact format:',
    'TITLE: <title>',
    'OBJECTIVE: <one or two sentences>',
    'STEPS:',
    '1. <step>',
    '2. <step>',
    '...',
    'DELIVERABLES:',
    '- <deliverable>',
    '...',
    'VERIFICATION:',
    '- <criterion>',
    '...',
    'TIME: <estimate>',
  ].join('\n');
}

/* ------------------------------------------------------------------ *
 * Response parsing
 * ------------------------------------------------------------------ */

/**
 * Parse the model's structured response into a GeneratedLab.
 *
 * The expected format is:
 *   TITLE: ...
 *   OBJECTIVE: ...
 *   STEPS:
 *   1. ...
 *   2. ...
 *   DELIVERABLES:
 *   - ...
 *   VERIFICATION:
 *   - ...
 *   TIME: ...
 *
 * The parser is robust to minor formatting variations: it locates each
 * section header by keyword, collects lines until the next header, and
 * splits list items on leading bullets or numbers. If a section is missing
 * or empty, the parser returns null so the caller falls back to the offline
 * template.
 */
function parseLab(
  text: string,
  req: LabGenerationRequest,
): GeneratedLab | null {
  const lines = text.split('\n');

  // Locate section boundaries by header keyword.
  const findSection = (keyword: string): number => {
    for (let i = 0; i < lines.length; i++) {
      const l = lines[i];
      if (l && l.trim().toUpperCase().startsWith(keyword)) {
        return i;
      }
    }
    return -1;
  };

  const titleIdx = findSection('TITLE:');
  const objectiveIdx = findSection('OBJECTIVE:');
  const stepsIdx = findSection('STEPS:');
  const deliverablesIdx = findSection('DELIVERABLES:');
  const verificationIdx = findSection('VERIFICATION:');
  const timeIdx = findSection('TIME:');

  // Required sections.
  if (titleIdx < 0 || objectiveIdx < 0 || stepsIdx < 0) return null;

  /** Extract the text after "KEYWORD:" on the same line, or the following line. */
  const extractInline = (idx: number): string => {
    const header = lines[idx];
    if (!header) return '';
    const after = header.split(':').slice(1).join(':').trim();
    if (after) return after;
    // Value may be on the next line.
    const next = lines[idx + 1];
    if (next && !next.match(/^\s*(STEPS|DELIVERABLES|VERIFICATION|TIME):/i)) {
      return next.trim();
    }
    return '';
  };

  /** Collect list/numbered items between two section indices. */
  const collectItems = (startIdx: number, endIdx: number): string[] => {
    const items: string[] = [];
    for (let i = startIdx + 1; i < endIdx; i++) {
      const raw = lines[i];
      if (!raw) continue;
      const line = raw.trim();
      if (!line) continue;
      // Stop if we hit another header.
      if (line.match(/^(TITLE|OBJECTIVE|STEPS|DELIVERABLES|VERIFICATION|TIME):/i)) {
        break;
      }
      // Strip leading bullet (-, *, •) or number prefix ("1. ", "1) ").
      const cleaned = line
        .replace(/^[-*•]\s+/, '')
        .replace(/^\d+[.)]\s+/, '')
        .trim();
      if (cleaned) items.push(cleaned);
    }
    return items;
  };

  const title = extractInline(titleIdx);
  const objective = extractInline(objectiveIdx);

  const stepsEnd =
    deliverablesIdx > stepsIdx
      ? deliverablesIdx
      : verificationIdx > stepsIdx
        ? verificationIdx
        : timeIdx > stepsIdx
          ? timeIdx
          : lines.length;
  const steps = collectItems(stepsIdx, stepsEnd);

  const deliverables =
    deliverablesIdx >= 0
      ? collectItems(
          deliverablesIdx,
          verificationIdx > deliverablesIdx
            ? verificationIdx
            : timeIdx > deliverablesIdx
              ? timeIdx
              : lines.length,
        )
      : [];

  const verification =
    verificationIdx >= 0
      ? collectItems(
          verificationIdx,
          timeIdx > verificationIdx ? timeIdx : lines.length,
        )
      : [];

  const estimatedTime =
    timeIdx >= 0 ? extractInline(timeIdx) : timeFor(req.difficulty);

  // Validate we got enough to be useful.
  if (!title || !objective || steps.length < 3) return null;

  return {
    title,
    category: req.category,
    difficulty: req.difficulty,
    objective,
    steps,
    deliverables: deliverables.length > 0 ? deliverables : ['A completed lab workbook.'],
    verificationCriteria:
      verification.length > 0
        ? verification
        : ['The lab steps are completed and evidence is captured.'],
    estimatedTime: estimatedTime || timeFor(req.difficulty),
    source: 'ollama',
  };
}

/* ------------------------------------------------------------------ *
 * Ollama call
 * ------------------------------------------------------------------ */

/** Shape of the Ollama /api/generate JSON response (only the fields we read). */
interface OllamaGenerateResponse {
  response?: string;
  error?: string;
}

/**
 * Generate a structured GRC lab exercise.
 *
 * Retrieves relevant knowledge base articles for the requested category,
 * checks whether a local Ollama model is available, and either generates the
 * lab with the model (grounded with the articles and the current findings
 * and risk register) or falls back to a deterministic offline template.
 *
 * On any error — Ollama unreachable, non-OK response, model error, or an
 * unparseable answer — the offline template is returned so the learner is
 * never left without a lab.
 *
 * @param req   The category, difficulty, and current environment state.
 * @param opts  Optional timeout override for the Ollama call.
 */
export async function generateLab(
  req: LabGenerationRequest,
  opts?: { timeoutMs?: number },
): Promise<GeneratedLab> {
  const timeoutMs = opts?.timeoutMs ?? 90000;

  // Try the generate call directly — no separate availability check.
  try {
    const citations = searchArticles(CATEGORY_LABEL[req.category], 3);
    const ctl = new AbortController();
    const timer = setTimeout(() => ctl.abort(), timeoutMs);
    const res = await fetch(OLLAMA_GENERATE_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: OLLAMA_MODEL,
        prompt: buildPrompt(req, citations),
        stream: false,
      }),
      signal: ctl.signal,
    });
    clearTimeout(timer);

    if (!res.ok) {
      console.warn('[Lab Generator] Ollama returned non-OK status:', res.status, res.statusText);
      return offlineLab(req);
    }

    const data = (await res.json()) as OllamaGenerateResponse;
    if (data.error) {
      console.warn('[Lab Generator] Ollama returned error:', data.error);
      return offlineLab(req);
    }

    const text = (data.response ?? '').trim();
    if (!text) {
      console.warn('[Lab Generator] Ollama returned empty response');
      return offlineLab(req);
    }

    const parsed = parseLab(text, req);
    if (!parsed) {
      console.warn('[Lab Generator] Failed to parse Ollama response');
      return offlineLab(req);
    }

    return parsed;
  } catch (err) {
    console.warn('[Lab Generator] Ollama fetch failed:', err);
    return offlineLab(req);
  }
}
