/**
 * Lab Generator window console for the GRC Range desktop.
 *
 * A UI window where the learner can generate custom GRC lab exercises using
 * Ollama. The learner picks a category and difficulty, then clicks "Generate
 * Lab". When a local Ollama model is available the lab is generated by the
 * model and grounded with the learner's findings and risk register; when
 * Ollama is offline a deterministic template lab is produced so the learner
 * always has a usable exercise.
 *
 * Layout (top to bottom):
 *  - Header: title "Lab Generator", subtitle, Ollama status indicator.
 *  - Configuration panel: category dropdown, difficulty dropdown, generate
 *    button.
 *  - Generated lab display: scrollable card with the lab title, badges,
 *    objective, steps, deliverables, verification criteria, estimated time,
 *    and action buttons (Save to Notepad, Regenerate, Print).
 *
 * Modeled on the GRC Senior Expert window (`@/ui/consoles/grcExpertWindow`)
 * but adapted for one-shot lab generation rather than chat.
 */

import type { GrcServices } from '@/vm/session';
import {
  LAB_CATEGORIES,
  LAB_DIFFICULTIES,
  labAvailable,
  generateLab,
  type LabCategory,
  type LabDifficulty,
  type GeneratedLab,
  type LabGenerationRequest,
} from '@/vm/labGenerator';
import { setLab } from '@/vm/currentLab';
import { warmUpModel } from '@/config/ollama';
import { getTheme } from '@/ui/themes';

/** Distinct badge color per lab category. */
const CATEGORY_COLORS: Record<LabCategory, string> = {
  audit: '#2f81f7',
  risk: '#d29922',
  remediation: '#3fb950',
  policy: '#a371f7',
  executive: '#39c5cf',
  compliance: '#6e7bf7',
  incident: '#f85149',
};

/** Badge color per difficulty level. */
const DIFFICULTY_COLORS: Record<LabDifficulty, string> = {
  Beginner: '#3fb950',
  Intermediate: '#d29922',
  Advanced: '#f85149',
};

/**
 * Render the Lab Generator window into the given body element.
 *
 * @param body     The window body element to populate.
 * @param services The GRC service bundle (used to build the request context).
 */
export function renderLabGeneratorWindow(
  body: HTMLElement,
  services: GrcServices,
): void {
  const theme = getTheme();

  body.style.fontFamily = "'Segoe UI', sans-serif";
  body.style.background = theme.surface;
  body.style.color = theme.text;
  body.style.display = 'flex';
  body.style.flexDirection = 'column';
  body.style.padding = '0';
  body.style.overflow = 'hidden';

  // Mutable window state ------------------------------------------------------
  let currentCategory: LabCategory = LAB_CATEGORIES[0]?.id ?? 'audit';
  let currentDifficulty: LabDifficulty = LAB_DIFFICULTIES[0] ?? 'Beginner';
  let ollamaOnline = false;
  let probed = false;
  let busy = false;
  let currentLab: GeneratedLab | null = null;

  // Header --------------------------------------------------------------------
  const header = document.createElement('div');
  header.style.padding = '10px 16px';
  header.style.background = theme.bg;
  header.style.borderBottom = `1px solid ${theme.border}`;
  header.style.display = 'flex';
  header.style.alignItems = 'center';
  header.style.gap = '12px';
  header.style.flexShrink = '0';

  const titleWrap = document.createElement('div');
  titleWrap.style.display = 'flex';
  titleWrap.style.flexDirection = 'column';
  titleWrap.style.gap = '2px';
  const title = document.createElement('div');
  title.textContent = 'Lab Generator';
  title.style.fontWeight = '600';
  title.style.fontSize = '15px';
  const subtitle = document.createElement('div');
  subtitle.textContent = 'AI-powered GRC exercise generation';
  subtitle.style.fontSize = '11px';
  subtitle.style.color = theme.textDim;
  titleWrap.appendChild(title);
  titleWrap.appendChild(subtitle);
  header.appendChild(titleWrap);

  // Ollama status indicator (right-aligned)
  const status = document.createElement('div');
  status.style.marginLeft = 'auto';
  status.style.display = 'flex';
  status.style.alignItems = 'center';
  status.style.gap = '6px';
  status.style.fontSize = '12px';
  status.style.color = theme.textDim;
  const statusDot = document.createElement('span');
  statusDot.style.width = '8px';
  statusDot.style.height = '8px';
  statusDot.style.borderRadius = '50%';
  statusDot.style.flexShrink = '0';
  const statusText = document.createElement('span');
  status.appendChild(statusDot);
  status.appendChild(statusText);
  header.appendChild(status);

  function renderStatus(): void {
    if (!probed) {
      statusDot.style.background = theme.warning;
      statusText.textContent = 'Checking Ollama…';
      statusText.style.color = theme.textDim;
      return;
    }
    if (ollamaOnline) {
      statusDot.style.background = theme.success;
      statusText.textContent = 'Ollama connected';
      statusText.style.color = theme.success;
    } else {
      statusDot.style.background = theme.textDim;
      statusText.textContent = 'Offline — template labs';
      statusText.style.color = theme.textDim;
    }
  }

  body.appendChild(header);

  // Configuration panel -------------------------------------------------------
  const configPanel = document.createElement('div');
  configPanel.style.padding = '14px 16px';
  configPanel.style.background = theme.bg;
  configPanel.style.borderBottom = `1px solid ${theme.border}`;
  configPanel.style.display = 'flex';
  configPanel.style.alignItems = 'flex-end';
  configPanel.style.gap = '12px';
  configPanel.style.flexShrink = '0';
  configPanel.style.flexWrap = 'wrap';

  // Category dropdown
  const catWrap = document.createElement('div');
  catWrap.style.display = 'flex';
  catWrap.style.flexDirection = 'column';
  catWrap.style.gap = '4px';
  const catLabel = document.createElement('label');
  catLabel.textContent = 'Category';
  catLabel.style.fontSize = '12px';
  catLabel.style.color = theme.textDim;
  catLabel.style.fontWeight = '600';
  const catSelect = document.createElement('select');
  catSelect.style.padding = '7px 10px';
  catSelect.style.borderRadius = '6px';
  catSelect.style.border = `1px solid ${theme.border}`;
  catSelect.style.background = theme.surface;
  catSelect.style.color = theme.text;
  catSelect.style.fontSize = '13px';
  catSelect.style.fontFamily = "'Segoe UI', sans-serif";
  catSelect.style.cursor = 'pointer';
  catSelect.style.outline = 'none';
  catSelect.style.minWidth = '200px';
  for (const cat of LAB_CATEGORIES) {
    const opt = document.createElement('option');
    opt.value = cat.id;
    opt.textContent = cat.label;
    opt.style.background = theme.surface;
    opt.style.color = theme.text;
    catSelect.appendChild(opt);
  }
  catSelect.addEventListener('focus', () => {
    catSelect.style.borderColor = theme.accent;
  });
  catSelect.addEventListener('blur', () => {
    catSelect.style.borderColor = theme.border;
  });
  catSelect.addEventListener('change', () => {
    currentCategory = catSelect.value as LabCategory;
  });
  catWrap.appendChild(catLabel);
  catWrap.appendChild(catSelect);
  configPanel.appendChild(catWrap);

  // Difficulty dropdown
  const diffWrap = document.createElement('div');
  diffWrap.style.display = 'flex';
  diffWrap.style.flexDirection = 'column';
  diffWrap.style.gap = '4px';
  const diffLabel = document.createElement('label');
  diffLabel.textContent = 'Difficulty';
  diffLabel.style.fontSize = '12px';
  diffLabel.style.color = theme.textDim;
  diffLabel.style.fontWeight = '600';
  const diffSelect = document.createElement('select');
  diffSelect.style.padding = '7px 10px';
  diffSelect.style.borderRadius = '6px';
  diffSelect.style.border = `1px solid ${theme.border}`;
  diffSelect.style.background = theme.surface;
  diffSelect.style.color = theme.text;
  diffSelect.style.fontSize = '13px';
  diffSelect.style.fontFamily = "'Segoe UI', sans-serif";
  diffSelect.style.cursor = 'pointer';
  diffSelect.style.outline = 'none';
  diffSelect.style.minWidth = '150px';
  for (const diff of LAB_DIFFICULTIES) {
    const opt = document.createElement('option');
    opt.value = diff;
    opt.textContent = diff;
    opt.style.background = theme.surface;
    opt.style.color = theme.text;
    diffSelect.appendChild(opt);
  }
  diffSelect.addEventListener('focus', () => {
    diffSelect.style.borderColor = theme.accent;
  });
  diffSelect.addEventListener('blur', () => {
    diffSelect.style.borderColor = theme.border;
  });
  diffSelect.addEventListener('change', () => {
    currentDifficulty = diffSelect.value as LabDifficulty;
  });
  diffWrap.appendChild(diffLabel);
  diffWrap.appendChild(diffSelect);
  configPanel.appendChild(diffWrap);

  // Generate button
  const generateBtn = document.createElement('button');
  generateBtn.textContent = 'Generate Lab';
  generateBtn.style.padding = '8px 20px';
  generateBtn.style.borderRadius = '6px';
  generateBtn.style.border = 'none';
  generateBtn.style.background = theme.accent;
  generateBtn.style.color = '#ffffff';
  generateBtn.style.fontWeight = '600';
  generateBtn.style.fontSize = '13px';
  generateBtn.style.cursor = 'pointer';
  generateBtn.style.transition = 'background 0.15s';
  generateBtn.style.marginLeft = 'auto';
  generateBtn.addEventListener('mouseenter', () => {
    if (!busy) generateBtn.style.background = theme.accentHover;
  });
  generateBtn.addEventListener('mouseleave', () => {
    if (!busy) generateBtn.style.background = theme.accent;
  });
  generateBtn.addEventListener('click', () => runGenerate());
  configPanel.appendChild(generateBtn);

  body.appendChild(configPanel);

  // Generated lab display (scrollable) ---------------------------------------
  const display = document.createElement('div');
  display.style.flex = '1';
  display.style.overflow = 'auto';
  display.style.padding = '16px';
  display.style.display = 'flex';
  display.style.flexDirection = 'column';
  display.style.gap = '12px';

  body.appendChild(display);

  // Helper: build a small badge element --------------------------------------
  function badge(text: string, color: string): HTMLElement {
    const b = document.createElement('span');
    b.textContent = text;
    b.style.display = 'inline-flex';
    b.style.alignItems = 'center';
    b.style.padding = '2px 10px';
    b.style.borderRadius = '12px';
    b.style.fontSize = '11px';
    b.style.fontWeight = '600';
    b.style.background = `${color}22`;
    b.style.color = color;
    b.style.border = `1px solid ${color}55`;
    b.style.whiteSpace = 'nowrap';
    return b;
  }

  // Helper: section heading ---------------------------------------------------
  function sectionHeading(text: string): HTMLElement {
    const h = document.createElement('div');
    h.textContent = text;
    h.style.fontSize = '13px';
    h.style.fontWeight = '700';
    h.style.color = theme.text;
    h.style.marginBottom = '6px';
    h.style.textTransform = 'uppercase';
    h.style.letterSpacing = '0.5px';
    return h;
  }

  // Helper: render the placeholder --------------------------------------------
  function renderPlaceholder(): void {
    display.innerHTML = '';
    const ph = document.createElement('div');
    ph.style.display = 'flex';
    ph.style.flexDirection = 'column';
    ph.style.alignItems = 'center';
    ph.style.justifyContent = 'center';
    ph.style.flex = '1';
    ph.style.gap = '12px';
    ph.style.color = theme.textDim;
    ph.style.textAlign = 'center';
    ph.style.padding = '40px 20px';

    const icon = document.createElement('div');
    icon.textContent = '\u2691';
    icon.style.fontSize = '48px';
    icon.style.opacity = '0.4';
    ph.appendChild(icon);

    const msg = document.createElement('div');
    msg.textContent =
      'Select a category and difficulty, then click Generate Lab to create a custom exercise.';
    msg.style.fontSize = '14px';
    msg.style.maxWidth = '420px';
    msg.style.lineHeight = '1.6';
    ph.appendChild(msg);

    display.appendChild(ph);
  }

  // Helper: render the loading state ------------------------------------------
  function renderLoading(): void {
    display.innerHTML = '';
    const wrap = document.createElement('div');
    wrap.style.display = 'flex';
    wrap.style.flexDirection = 'column';
    wrap.style.alignItems = 'center';
    wrap.style.justifyContent = 'center';
    wrap.style.flex = '1';
    wrap.style.gap = '16px';

    const spinner = document.createElement('div');
    spinner.style.width = '36px';
    spinner.style.height = '36px';
    spinner.style.border = `3px solid ${theme.border}`;
    spinner.style.borderTopColor = theme.accent;
    spinner.style.borderRadius = '50%';
    spinner.style.animation = 'grc-lab-spin 0.8s linear infinite';

    const text = document.createElement('div');
    text.textContent = 'Generating lab...';
    text.style.fontSize = '14px';
    text.style.color = theme.textDim;

    wrap.appendChild(spinner);
    wrap.appendChild(text);
    display.appendChild(wrap);
  }

  // Helper: render an error state ---------------------------------------------
  function renderError(message: string): void {
    display.innerHTML = '';
    const wrap = document.createElement('div');
    wrap.style.display = 'flex';
    wrap.style.flexDirection = 'column';
    wrap.style.alignItems = 'center';
    wrap.style.justifyContent = 'center';
    wrap.style.flex = '1';
    wrap.style.gap = '12px';
    wrap.style.padding = '40px 20px';
    wrap.style.textAlign = 'center';

    const icon = document.createElement('div');
    icon.textContent = '\u26a0';
    icon.style.fontSize = '36px';
    icon.style.color = theme.danger;
    wrap.appendChild(icon);

    const msg = document.createElement('div');
    msg.textContent = message;
    msg.style.fontSize = '14px';
    msg.style.color = theme.danger;
    msg.style.maxWidth = '420px';
    msg.style.lineHeight = '1.6';
    wrap.appendChild(msg);

    display.appendChild(wrap);
  }

  // Helper: render the generated lab card ------------------------------------
  function renderLab(lab: GeneratedLab): void {
    display.innerHTML = '';

    const card = document.createElement('div');
    card.style.background = theme.surfaceElevated;
    card.style.border = `1px solid ${theme.border}`;
    card.style.borderRadius = '10px';
    card.style.padding = '20px 24px';
    card.style.boxShadow = '0 4px 16px rgba(0,0,0,0.25)';

    // Title row with badges
    const titleRow = document.createElement('div');
    titleRow.style.display = 'flex';
    titleRow.style.alignItems = 'flex-start';
    titleRow.style.justifyContent = 'space-between';
    titleRow.style.gap = '12px';
    titleRow.style.marginBottom = '14px';
    titleRow.style.flexWrap = 'wrap';

    const labTitle = document.createElement('div');
    labTitle.textContent = lab.title;
    labTitle.style.fontSize = '19px';
    labTitle.style.fontWeight = '700';
    labTitle.style.color = theme.text;
    labTitle.style.flex = '1';
    labTitle.style.lineHeight = '1.3';
    titleRow.appendChild(labTitle);

    const badgeRow = document.createElement('div');
    badgeRow.style.display = 'flex';
    badgeRow.style.alignItems = 'center';
    badgeRow.style.gap = '6px';
    badgeRow.style.flexWrap = 'wrap';
    badgeRow.appendChild(
      badge(
        lab.source === 'ollama' ? 'AI Generated' : 'Template',
        lab.source === 'ollama' ? theme.accent : theme.textDim,
      ),
    );
    badgeRow.appendChild(badge(lab.difficulty, DIFFICULTY_COLORS[lab.difficulty]));
    titleRow.appendChild(badgeRow);

    card.appendChild(titleRow);

    // Category tag
    const catTag = badge(
      LAB_CATEGORIES.find((c) => c.id === lab.category)?.label ?? lab.category,
      CATEGORY_COLORS[lab.category],
    );
    catTag.style.marginBottom = '16px';
    card.appendChild(catTag);

    // Objective
    const objHeading = sectionHeading('Objective');
    card.appendChild(objHeading);
    const objText = document.createElement('div');
    objText.textContent = lab.objective;
    objText.style.fontSize = '13px';
    objText.style.lineHeight = '1.6';
    objText.style.color = theme.text;
    objText.style.marginBottom = '18px';
    card.appendChild(objText);

    // Steps (numbered list)
    if (lab.steps.length > 0) {
      card.appendChild(sectionHeading('Steps'));
      const stepsList = document.createElement('ol');
      stepsList.style.margin = '0 0 18px 0';
      stepsList.style.padding = '0 0 0 24px';
      stepsList.style.display = 'flex';
      stepsList.style.flexDirection = 'column';
      stepsList.style.gap = '8px';
      for (const step of lab.steps) {
        const li = document.createElement('li');
        li.textContent = step;
        li.style.fontSize = '13px';
        li.style.lineHeight = '1.55';
        li.style.color = theme.text;
        li.style.paddingLeft = '4px';
        stepsList.appendChild(li);
      }
      card.appendChild(stepsList);
    }

    // Deliverables (bullet list with checkmark icons)
    if (lab.deliverables.length > 0) {
      card.appendChild(sectionHeading('Deliverables'));
      const delList = document.createElement('ul');
      delList.style.listStyle = 'none';
      delList.style.margin = '0 0 18px 0';
      delList.style.padding = '0';
      delList.style.display = 'flex';
      delList.style.flexDirection = 'column';
      delList.style.gap = '8px';
      for (const del of lab.deliverables) {
        const li = document.createElement('li');
        li.style.display = 'flex';
        li.style.alignItems = 'flex-start';
        li.style.gap = '8px';
        li.style.fontSize = '13px';
        li.style.lineHeight = '1.55';
        li.style.color = theme.text;
        const check = document.createElement('span');
        check.textContent = '\u2713';
        check.style.color = theme.success;
        check.style.fontWeight = '700';
        check.style.flexShrink = '0';
        check.style.marginTop = '1px';
        const span = document.createElement('span');
        span.textContent = del;
        li.appendChild(check);
        li.appendChild(span);
        delList.appendChild(li);
      }
      card.appendChild(delList);
    }

    // Verification Criteria (bullet list)
    if (lab.verificationCriteria.length > 0) {
      card.appendChild(sectionHeading('Verification Criteria'));
      const vcList = document.createElement('ul');
      vcList.style.listStyle = 'none';
      vcList.style.margin = '0 0 18px 0';
      vcList.style.padding = '0';
      vcList.style.display = 'flex';
      vcList.style.flexDirection = 'column';
      vcList.style.gap = '8px';
      for (const vc of lab.verificationCriteria) {
        const li = document.createElement('li');
        li.style.display = 'flex';
        li.style.alignItems = 'flex-start';
        li.style.gap = '8px';
        li.style.fontSize = '13px';
        li.style.lineHeight = '1.55';
        li.style.color = theme.text;
        const dot = document.createElement('span');
        dot.textContent = '\u2022';
        dot.style.color = theme.accent;
        dot.style.fontWeight = '700';
        dot.style.flexShrink = '0';
        dot.style.marginTop = '1px';
        const span = document.createElement('span');
        span.textContent = vc;
        li.appendChild(dot);
        li.appendChild(span);
        vcList.appendChild(li);
      }
      card.appendChild(vcList);
    }

    // Estimated Time (with clock icon)
    const timeRow = document.createElement('div');
    timeRow.style.display = 'flex';
    timeRow.style.alignItems = 'center';
    timeRow.style.gap = '8px';
    timeRow.style.marginBottom = '20px';
    const clock = document.createElement('span');
    clock.textContent = '\u23f1';
    clock.style.fontSize = '15px';
    const timeLabel = document.createElement('span');
    timeLabel.textContent = 'Estimated Time:';
    timeLabel.style.fontSize = '13px';
    timeLabel.style.fontWeight = '600';
    timeLabel.style.color = theme.textDim;
    const timeValue = document.createElement('span');
    timeValue.textContent = lab.estimatedTime;
    timeValue.style.fontSize = '13px';
    timeValue.style.color = theme.text;
    timeRow.appendChild(clock);
    timeRow.appendChild(timeLabel);
    timeRow.appendChild(timeValue);
    card.appendChild(timeRow);

    // Action buttons
    const actionRow = document.createElement('div');
    actionRow.style.display = 'flex';
    actionRow.style.gap = '10px';
    actionRow.style.flexWrap = 'wrap';
    actionRow.style.paddingTop = '16px';
    actionRow.style.borderTop = `1px solid ${theme.borderSubtle}`;

    // Save to Notepad
    const saveBtn = document.createElement('button');
    saveBtn.textContent = 'Save to Notepad';
    saveBtn.style.padding = '7px 16px';
    saveBtn.style.borderRadius = '6px';
    saveBtn.style.border = `1px solid ${theme.border}`;
    saveBtn.style.background = theme.surface;
    saveBtn.style.color = theme.text;
    saveBtn.style.fontSize = '12px';
    saveBtn.style.fontWeight = '600';
    saveBtn.style.cursor = 'pointer';
    saveBtn.style.transition = 'background 0.15s, border 0.15s';
    saveBtn.addEventListener('mouseenter', () => {
      saveBtn.style.background = theme.surfaceHover;
      saveBtn.style.borderColor = theme.accent;
    });
    saveBtn.addEventListener('mouseleave', () => {
      saveBtn.style.background = theme.surface;
      saveBtn.style.borderColor = theme.border;
    });
    saveBtn.addEventListener('click', () => saveLab(lab, saveBtn));
    actionRow.appendChild(saveBtn);

    // Regenerate
    const regenBtn = document.createElement('button');
    regenBtn.textContent = 'Regenerate';
    regenBtn.style.padding = '7px 16px';
    regenBtn.style.borderRadius = '6px';
    regenBtn.style.border = `1px solid ${theme.border}`;
    regenBtn.style.background = theme.surface;
    regenBtn.style.color = theme.text;
    regenBtn.style.fontSize = '12px';
    regenBtn.style.fontWeight = '600';
    regenBtn.style.cursor = 'pointer';
    regenBtn.style.transition = 'background 0.15s, border 0.15s';
    regenBtn.addEventListener('mouseenter', () => {
      regenBtn.style.background = theme.surfaceHover;
      regenBtn.style.borderColor = theme.accent;
    });
    regenBtn.addEventListener('mouseleave', () => {
      regenBtn.style.background = theme.surface;
      regenBtn.style.borderColor = theme.border;
    });
    regenBtn.addEventListener('click', () => runGenerate());
    actionRow.appendChild(regenBtn);

    // Start this lab (sets it as current and guides to GRC Expert)
    const startBtn = document.createElement('button');
    startBtn.textContent = 'Start this lab';
    startBtn.style.padding = '7px 16px';
    startBtn.style.borderRadius = '6px';
    startBtn.style.border = `1px solid ${theme.accent}`;
    startBtn.style.background = theme.accent;
    startBtn.style.color = '#ffffff';
    startBtn.style.fontSize = '12px';
    startBtn.style.fontWeight = '600';
    startBtn.style.cursor = 'pointer';
    startBtn.style.transition = 'background 0.15s, border 0.15s';
    startBtn.addEventListener('mouseenter', () => {
      startBtn.style.background = theme.accentHover;
    });
    startBtn.addEventListener('mouseleave', () => {
      startBtn.style.background = theme.accent;
    });
    startBtn.addEventListener('click', () => {
      setLab(lab);
      flashButton(startBtn, 'Lab started! Open GRC Expert for guidance');
    });
    actionRow.appendChild(startBtn);

    // Print
    const printBtn = document.createElement('button');
    printBtn.textContent = 'Print';
    printBtn.style.padding = '7px 16px';
    printBtn.style.borderRadius = '6px';
    printBtn.style.border = `1px solid ${theme.border}`;
    printBtn.style.background = theme.surface;
    printBtn.style.color = theme.text;
    printBtn.style.fontSize = '12px';
    printBtn.style.fontWeight = '600';
    printBtn.style.cursor = 'pointer';
    printBtn.style.transition = 'background 0.15s, border 0.15s';
    printBtn.addEventListener('mouseenter', () => {
      printBtn.style.background = theme.surfaceHover;
      printBtn.style.borderColor = theme.accent;
    });
    printBtn.addEventListener('mouseleave', () => {
      printBtn.style.background = theme.surface;
      printBtn.style.borderColor = theme.border;
    });
    printBtn.addEventListener('click', () => printLab(lab));
    actionRow.appendChild(printBtn);

    card.appendChild(actionRow);

    display.appendChild(card);
  }

  // Save lab to clipboard (fallback to alert) ---------------------------------
  function saveLab(lab: GeneratedLab, btn: HTMLButtonElement): void {
    const text = formatLabText(lab);
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard
        .writeText(text)
        .then(() => flashButton(btn, 'Copied!'))
        .catch(() => {
          window.alert(text);
        });
    } else {
      window.alert(text);
    }
  }

  // Print lab via a hidden iframe ---------------------------------------------
  function printLab(lab: GeneratedLab): void {
    const html = formatLabHtml(lab);
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);
    const doc = iframe.contentWindow?.document;
    if (!doc) {
      iframe.remove();
      return;
    }
    doc.open();
    doc.write(html);
    doc.close();
    iframe.contentWindow?.focus();
    iframe.contentWindow?.print();
    setTimeout(() => iframe.remove(), 1000);
  }

  // Plain-text representation of a lab ----------------------------------------
  function formatLabText(lab: GeneratedLab): string {
    const lines: string[] = [];
    lines.push(lab.title);
    lines.push('');
    lines.push(
      `Category: ${LAB_CATEGORIES.find((c) => c.id === lab.category)?.label ?? lab.category}`,
    );
    lines.push(`Difficulty: ${lab.difficulty}`);
    lines.push(`Source: ${lab.source === 'ollama' ? 'AI Generated' : 'Template'}`);
    lines.push(`Estimated Time: ${lab.estimatedTime}`);
    lines.push('');
    lines.push('OBJECTIVE');
    lines.push(lab.objective);
    lines.push('');
    if (lab.steps.length > 0) {
      lines.push('STEPS');
      lab.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      lines.push('');
    }
    if (lab.deliverables.length > 0) {
      lines.push('DELIVERABLES');
      lab.deliverables.forEach((d) => lines.push(`- ${d}`));
      lines.push('');
    }
    if (lab.verificationCriteria.length > 0) {
      lines.push('VERIFICATION CRITERIA');
      lab.verificationCriteria.forEach((v) => lines.push(`- ${v}`));
    }
    return lines.join('\n');
  }

  // HTML representation of a lab for printing ---------------------------------
  function formatLabHtml(lab: GeneratedLab): string {
    const catLabel =
      LAB_CATEGORIES.find((c) => c.id === lab.category)?.label ?? lab.category;
    const steps = lab.steps.map((s) => `<li>${escapeHtml(s)}</li>`).join('');
    const dels = lab.deliverables
      .map((d) => `<li>${escapeHtml(d)}</li>`)
      .join('');
    const vcs = lab.verificationCriteria
      .map((v) => `<li>${escapeHtml(v)}</li>`)
      .join('');
    return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(lab.title)}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; max-width: 760px; margin: 32px auto; padding: 0 24px; line-height: 1.6; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .meta { color: #555; font-size: 13px; margin-bottom: 20px; }
  .meta span { margin-right: 16px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 24px; }
  ol, ul { padding-left: 24px; }
  li { margin-bottom: 6px; font-size: 13px; }
</style>
</head>
<body>
  <h1>${escapeHtml(lab.title)}</h1>
  <div class="meta">
    <span><strong>Category:</strong> ${escapeHtml(catLabel)}</span>
    <span><strong>Difficulty:</strong> ${escapeHtml(lab.difficulty)}</span>
    <span><strong>Estimated Time:</strong> ${escapeHtml(lab.estimatedTime)}</span>
  </div>
  <h2>Objective</h2>
  <p>${escapeHtml(lab.objective)}</p>
  ${steps ? `<h2>Steps</h2><ol>${steps}</ol>` : ''}
  ${dels ? `<h2>Deliverables</h2><ul>${dels}</ul>` : ''}
  ${vcs ? `<h2>Verification Criteria</h2><ul>${vcs}</ul>` : ''}
</body>
</html>`;
  }

  // Escape HTML special characters -------------------------------------------
  function escapeHtml(s: string): string {
    return s
      .replace(/&/g, '\u0026amp;')
      .replace(/</g, '\u0026lt;')
      .replace(/>/g, '\u0026gt;')
      .replace(/"/g, '\u0026quot;')
      .replace(/'/g, '\u0026#39;');
  }

  // Briefly flash a button's label -------------------------------------------
  function flashButton(btn: HTMLButtonElement, msg: string): void {
    const original = btn.textContent;
    btn.textContent = msg;
    btn.style.borderColor = theme.success;
    btn.style.color = theme.success;
    setTimeout(() => {
      btn.textContent = original;
      btn.style.borderColor = theme.border;
      btn.style.color = theme.text;
    }, 1500);
  }

  // Build the generation request from current settings -----------------------
  function buildRequest(
    category: LabCategory,
    difficulty: LabDifficulty,
  ): LabGenerationRequest {
    return {
      category,
      difficulty,
      findings: services.compliance
        .listFindings()
        .map((f) => ({
          id: f.id,
          title: f.title,
          severity: f.severity,
          status: f.status,
        })),
      risks: services.compliance
        .listRisks()
        .map((r) => ({
          id: r.id,
          finding: r.finding,
          inherentRisk: r.inherentRisk,
        })),
    };
  }

  // Run the generation flow ---------------------------------------------------
  function runGenerate(): void {
    if (busy) return;
    busy = true;
    generateBtn.disabled = true;
    generateBtn.style.opacity = '0.6';
    generateBtn.textContent = 'Generating…';
    renderLoading();

    const req = buildRequest(currentCategory, currentDifficulty);
    generateLab(req)
      .then((lab: GeneratedLab) => {
        currentLab = lab;
        setLab(lab);
        renderLab(lab);
      })
      .catch(() => {
        renderError(
          'Lab generation failed. The offline fallback should always produce a lab — please try again.',
        );
      })
      .finally(() => {
        busy = false;
        generateBtn.disabled = false;
        generateBtn.style.opacity = '1';
        generateBtn.textContent = 'Generate Lab';
      });
  }

  // Spinner keyframes (injected once) ----------------------------------------
  const styleId = 'grc-lab-generator-spin';
  if (!document.getElementById(styleId)) {
    const styleEl = document.createElement('style');
    styleEl.id = styleId;
    styleEl.textContent =
      '@keyframes grc-lab-spin { to { transform: rotate(360deg); } }';
    document.head.appendChild(styleEl);
  }

  // Boot ----------------------------------------------------------------------
  renderPlaceholder();
  renderStatus();

  // Probe Ollama availability on window open, and warm up the model.
  labAvailable()
    .then((ok) => {
      ollamaOnline = ok;
      probed = true;
      renderStatus();
      // Pre-load the model so the first lab generation is fast.
      if (ok) void warmUpModel();
    })
    .catch(() => {
      ollamaOnline = false;
      probed = true;
      renderStatus();
    });
}
